# Generated by Django 3.0.2 on 2020-01-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=255)),
                ('cutting_permit', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbh', models.IntegerField()),
                ('gross_piece_size', models.DecimalField(decimal_places=3, max_digits=9)),
                ('height', models.IntegerField()),
                ('net_piece_size', models.DecimalField(decimal_places=3, max_digits=9)),
                ('species', models.CharField(choices=[('PL', 'Pine'), ('SX', 'Spruce'), ('BL', 'Balsam'), ('FD', 'Douglas Fir')], default='PL', max_length=255)),
                ('tree', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plotses', to='core.Location')),
            ],
        ),
    ]
