# Generated by Django 3.0.2 on 2020-01-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='userkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plotses', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='plotdata',
            name='plot_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_datas', to='core.Plots'),
        ),
        migrations.AddField(
            model_name='latlong',
            name='location_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lat_longs', to='core.Location'),
        ),
    ]
