# Generated by Django 3.0.2 on 2020-01-27 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200127_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='userkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot', to=settings.AUTH_USER_MODEL),
        ),
    ]
