# Generated by Django 3.0.2 on 2020-02-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200207_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='fiz',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='vol_const_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='vol_const_b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='vol_const_c',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
