# Generated by Django 3.0.2 on 2020-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200219_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdata',
            name='alive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
