# Generated by Django 3.0.2 on 2020-02-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plotdata_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='vol_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
