# Generated by Django 3.0.2 on 2020-02-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_species_vol_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='sigma_squared',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
