# Generated by Django 3.0.2 on 2020-02-26 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200222_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='bec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='core.Zone'),
        ),
    ]
