# Generated by Django 3.0.2 on 2020-02-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200225_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='fiz',
            new_name='bec',
        ),
    ]
