# Generated by Django 3.0.2 on 2020-03-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200225_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='loss_factor_dead',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
